seed: 1445
checkpoint_restore: './data/logs/best_rouge_l_checkpoint.pt'
validation_test_path: './data/results/test.data'
#validation_test_path: './data/results/validation.data'
vocab_path: './data/preprocessed/dataset_50k_600/vocab_50000'
beam_size: 5
shuffle: False
num_workers: 1
gpus: [0]
pointer_gen: True
is_coverage: False
is_semantic_similary: False
model: 'seq2seq'
optim: 'AdagradCustom'
use_cuda: True
trunc_norm_init_std: 0.0001
rand_unif_init_mag: 0.02
use_maxpool_init_ctx: False
eps: 0.000000000001
cov_loss_wt: 1.0
share_vocab: True
emb_dim: 300
hidden_dim: 256
encoder_num_layers: 1
dropout: 0.5
encoder_bidirec: True
decoder_num_layers: 1
decoder_hidden_size: 512
global_emb: False
max_dec_steps: 14
min_dec_steps: 5
