test: False
aug: False
max_enc_steps: 200
max_dec_steps: 20
pointer_gen: True
coverage: False
train_path: '../data/preprocessed/train_set_last_all.csv'
val_path: '../data/preprocessed/val_set_last_1000.csv'
test_path: '../data/preprocessed/test_set_last_1000.csv'
vocab_path: '../data/preprocessed/vocab_200000'
pre_word_embedding_path: '../data/embedding/GoogleNews-vectors-negative300.bin'
save: True
max_size: 50004
train_data_path: '../data/preprocessed/dataset_50k_200/train.data'
val_data_path: '../data/preprocessed/dataset_50k_200/val.data'
test_data_path: '../data/preprocessed/dataset_50k_200/test.data'
vocab_path_50: '../data/preprocessed/dataset_50k_200/vocab_50000'
